version: '3'
services:
  mysqldb:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: mysqldb-inventory-service
    ports:
      - "3307:3307"
    expose:
      - "3307"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: inventory
      MYSQL_TCP_PORT: 3307