server:
  port: 8282

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/inventory?useSSL=false
    username: root
    password: admin
    initialization-mode: always
  application:
    name: inventory-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: configserver:http://localhost:8888
  cloud:
    vault:
      host: localhost
      port: 8200
      scheme: http
      authentication: token
      token: s.aGR7G5fKRGHFj1JtDeMHeMJ7
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.example: debug